preload = $HOME/Pictures/壁纸/jpgs/a.jpg
preload = $HOME/Pictures/壁纸/jpgs/b.jpg
preload = $HOME/Pictures/壁纸/jpgs/c.jpg
preload = $HOME/Pictures/壁纸/jpgs/d.jpg
preload = $HOME/Pictures/壁纸/jpgs/e.jpg
preload = $HOME/Pictures/壁纸/jpgs/f.jpg
preload = $HOME/Pictures/壁纸/jpgs/g.jpg

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
# wallpaper = HDMI-A-1,$HOME/Pictures/壁纸/jpgs/a.jpg
wallpaper = eDP-1,$HOME/Pictures/壁纸/jpgs/a.jpg

#enable splash text rendering over the wallpaper
splash = true
